# Generated by Django 5.2 on 2025-04-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
    ]
