# Generated by Django 5.2 on 2025-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_rename_interests_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=models.TextField(),
        ),
    ]
