# Generated by Django 5.2 on 2025-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0003_alter_interest_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('location', models.CharField(max_length=65)),
                ('comment', models.CharField()),
            ],
        ),
    ]
