# Generated by Django 5.2.1 on 2025-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
