# Generated by Django 5.2.1 on 2025-06-08 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customuser_avatar_address_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
